<?xml version="1.0" encoding="utf-8"?><Database Name="Monitoring" Class="MonitoringDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HERNAN-PC\SQLEXPRESS08;Initial Catalog=Monitoring;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MonitoringConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FakeData" Member="FakeDatas">
    <Type Name="FakeData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Metric" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EventDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>